var whatsappRoutes = [
    {
        path:'/',
        redirect:'/allchats'
    },
    {
        path:'/allchats',
        name:'allchats',
        component:chat_contacts_controller
    },
    {
        path:'/status',
        name:'status',
        component:status_controller
    },
    {
        path:'/channels',
        name:'channels',
        component:channels_controller
    },
    {
        path:'/community',
        name:'community',
        component:community_controller
    },
    {
        path:'/settings',
        name:'settings',
        component:settings_controller
    },
    {
        path:'/profile',
        name:'profile',
        component:profile_controller
    },
    {
        path:'/newchat',
        name:'newchat',
        component:profile_controller
    }
]
